In [8]:
import numpy as np
A=np.array([10, 20, 30, 40, 50])
B=np.array([5, 4, 3, 2 , 1])
print(A+B)
print(A-B)
print(A*B)
print(A/B)

[15 24 33 42 51]
[ 5 16 27 38 49]
[50 80 90 80 50]
[ 2.  5. 10. 20. 50.]


In [9]:
print(A.min())
print(A.max())
print(A.mean())

10
50
30.0


In [11]:
dot_product_of_A=(np.dot(A,A))
print(dot_product_of_A)
dot_product_of_B=(np.dot(B,B))
print(dot_product_of_B)


5500
55


In [12]:
reshape_A=np.reshape(A,(5,1))
print(reshape_A)

[[10]
 [20]
 [30]
 [40]
 [50]]
